webserver:
  build: webserver
  volumes:
    - ../docroot/:/var/www/html/
  links:
    - database
  ports:
    - 80:80

database:
  image: mariadb:10.1
  volumes:
    - /var/lib/mysql/
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
